manifest:
  remotes:
    - name: Preacher325
      url-base: https://github.com/Preacher325
  projects:
    - name: Pimoroni_ZMK
      remote: Preacher325
      revision: Attempt_1_B2_Remote_Call
      import: app/west.yml
  self:
    path: config
